// Copyright 2026 Ravel Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Processors for synthetic shell nodes (`comp.*`) generated by the shell
//! compiler ([`ravel_core::composition::compile`]).
//!
//! Every shell processor resolves its owning layer from the [`Document`] at
//! process time — decoding the deterministic node id — so layer edits only
//! require cache invalidation, never a processor rebuild.

mod background;
mod merge;
mod opacity;
mod transform;

pub use background::CompBackgroundProcessor;
pub use merge::{CompMergeGpuProcessor, CompMergeProcessor};
pub use opacity::{CompOpacityGpuProcessor, CompOpacityProcessor};
pub use transform::{CompTransformGpuProcessor, CompTransformProcessor};

use ravel_core::composition::compile::{NodeRole, decode_deterministic_node_id};
use ravel_core::composition::{Composition, Layer};
use ravel_core::eval::{EvalContext, EvalScope, NodeProcessor, PathSegment, ResolvedParams};
use ravel_core::graph::Node;
use ravel_core::network as net;
use ravel_core::types::{FrameBuffer, NodeData, PortRecord};
use std::sync::Arc;

use crate::scaled_resolution;

// ===========================================================================
// Shared helpers
// ===========================================================================

/// Resolve the composition owning a shell node from its deterministic id,
/// checking the encoded role.
pub(crate) fn shell_layer(
    node: &Node,
    scope: &mut dyn EvalScope,
    expected: NodeRole,
) -> anyhow::Result<(Arc<Composition>, ravel_core::id::LayerId)> {
    let key = &node.type_key;
    let (comp_id, layer_id, role) = decode_deterministic_node_id(node.id)
        .ok_or_else(|| anyhow::anyhow!("{key}: non-deterministic node id"))?;
    anyhow::ensure!(role == expected, "{key}: node id role mismatch");
    let document = scope
        .document()
        .ok_or_else(|| anyhow::anyhow!("{key}: no document set on the evaluator"))?;
    let comp = document
        .get_composition(comp_id)
        .ok_or_else(|| anyhow::anyhow!("{key}: composition {comp_id:?} missing"))?
        .clone();
    Ok((comp, layer_id))
}

/// The layer-local frame for channel evaluation (REQ-LAYER-006).
///
/// Continuous: the shell's channels are sampled at the context's sub-frame
/// position, not at the enclosing integer frame.
pub(crate) fn layer_local_frame(layer: &Layer, ctx: &EvalContext) -> f64 {
    layer.local_frame_continuous(ctx.sample_frame())
}

pub(crate) fn transparent(ctx: &EvalContext) -> Arc<dyn NodeData> {
    Arc::new(FrameBuffer::new_zeroed(ctx.resolution.0, ctx.resolution.1))
}

/// The context a layer's own network is evaluated in: composition time
/// rebased onto the layer's local timeline (REQ-LAYER-006).
///
/// `frame` is the integer local index — keyframe addressing and the
/// `[in, out)` range check both work on it. `time` carries the parent's
/// sub-frame offset through unchanged, so an animated parameter *inside* the
/// network moves within a frame instead of returning the enclosing frame's
/// value N times. Dropping the offset here would quantise the whole layer
/// network, which is the case motion blur exists for.
fn layer_network_context(
    comp: &Composition,
    local_frame: i64,
    ctx: &EvalContext,
    resolution: (u32, u32),
) -> EvalContext {
    let sub_frame = ctx.sample_frame() - ctx.frame as f64;
    EvalContext {
        frame: local_frame as u64,
        time: (local_frame as f64 + sub_frame) / comp.frame_rate.as_f64(),
        fps: comp.frame_rate,
        resolution,
        comp_resolution: comp.resolution,
    }
}

// ===========================================================================
// comp.network — layer network boundary (REQ-LAYER-006/007)
// ===========================================================================

/// Evaluates the owning layer's network under layer-local time and returns
/// the network's `frame` output. Outside the layer's display interval the
/// network is not evaluated and a transparent frame is produced.
pub struct CompNetworkProcessor;

impl CompNetworkProcessor {
    pub fn from_node(_node: &Node) -> Self {
        Self
    }
}

impl NodeProcessor for CompNetworkProcessor {
    fn process(
        &self,
        node: &Node,
        ctx: &EvalContext,
        inputs: &[Option<Arc<dyn NodeData>>],
        _params: &ResolvedParams,
        scope: &mut dyn EvalScope,
    ) -> anyhow::Result<Arc<dyn NodeData>> {
        let (comp, layer_id) = shell_layer(node, scope, NodeRole::Network)?;
        let layer = comp
            .get_layer(layer_id)
            .ok_or_else(|| anyhow::anyhow!("comp.network: layer {layer_id:?} missing"))?;
        let resolution = scaled_resolution(ctx, comp.resolution);

        let transparent = || -> Arc<dyn NodeData> {
            Arc::new(FrameBuffer::new_zeroed(resolution.0, resolution.1))
        };

        // Layer-local frame: comp_frame - start_frame + in_frame
        // (REQ-LAYER-006). Outside [in, out) the network is not evaluated.
        let local_frame = ctx.frame as i64 - layer.start_frame + layer.in_frame as i64;
        if local_frame < layer.in_frame as i64 || local_frame >= layer.out_frame as i64 {
            return Ok(transparent());
        }

        let out_node = net::find_out_node(&layer.network)
            .ok_or_else(|| anyhow::anyhow!("comp.network: layer network has no net.out node"))?;
        let frame_index = net::frame_port_index(out_node)
            .ok_or_else(|| anyhow::anyhow!("comp.network: net.out has no frame port"))?;

        let local = layer_network_context(&comp, local_frame, ctx, resolution);

        let mut bindings: Vec<(String, Arc<dyn NodeData>)> = Vec::new();
        if layer.adjustment
            && let Some(source) = inputs.first().and_then(|i| i.clone())
        {
            bindings.push((net::PORT_SOURCE.to_string(), source));
        }

        let comp_id = comp.id;
        let value = scope.evaluate_sub(
            PathSegment::Layer(comp_id, layer_id),
            &layer.network,
            out_node.id,
            &local,
            bindings,
        )?;

        // net.out always produces a PortRecord (one entry per input port);
        // extract the `frame` entry.
        value
            .downcast_ref::<PortRecord>()
            .and_then(|record| record.0.get(frame_index).cloned())
            .ok_or_else(|| anyhow::anyhow!("comp.network: net.out did not produce a frame record"))
    }

    fn is_time_dependent(&self) -> bool {
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ravel_core::id::CompId;
    use ravel_core::types::FrameRate;

    const FPS: FrameRate = FrameRate { num: 30, den: 1 };

    fn comp() -> Composition {
        Composition::new(CompId::new(1), "Comp", (1920, 1080), FPS, 300)
    }

    #[test]
    fn layer_network_context_is_unchanged_on_the_frame_grid() {
        let comp = comp();
        let parent = EvalContext::new(20, FPS, (1920, 1080));
        let local = layer_network_context(&comp, 8, &parent, (1920, 1080));
        assert_eq!(local.frame, 8);
        assert_eq!(local.time, 8.0 / FPS.as_f64());
        assert_eq!(local.sample_frame(), 8.0);
    }

    #[test]
    fn layer_network_context_carries_the_parents_sub_frame_offset() {
        // Quantising the boundary would make every shutter sample inside a
        // layer network return the same value.
        let comp = comp();
        let mut parent = EvalContext::new(20, FPS, (1920, 1080));
        parent.time += 0.25 / FPS.as_f64();

        let local = layer_network_context(&comp, 8, &parent, (1920, 1080));
        assert_eq!(
            local.frame, 8,
            "the integer index still addresses keyframes"
        );
        assert!(
            (local.sample_frame() - 8.25).abs() < 1e-9,
            "sub-frame offset was dropped: {}",
            local.sample_frame()
        );
    }

    #[test]
    fn layer_network_context_rebases_onto_the_layers_own_timeline() {
        let comp = comp();
        let mut parent = EvalContext::new(20, FPS, (1920, 1080));
        parent.time += 0.5 / FPS.as_f64();

        // A layer starting at comp frame 12 sees its own frame 8.5.
        let local = layer_network_context(&comp, 20 - 12, &parent, (1920, 1080));
        assert!((local.sample_frame() - 8.5).abs() < 1e-9);
    }
}
