// Copyright 2026 Ravel Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Processors for synthetic nodes generated by the Composition compiler.
//!
//! These handle the `comp.*` type keys emitted by
//! [`ravel_core::composition::compile::compile_composition`].

mod source;
mod time_offset;

pub use source::CompSourceProcessor;
pub use time_offset::TimeOffsetProcessor;

use ravel_core::eval::{EvalContext, NodeProcessor};
use ravel_core::graph::Node;
use ravel_core::types::NodeData;

// ===========================================================================
// Pass-through processors for nodes that will gain real implementations
// when GPU evaluation is wired up.
// ===========================================================================

/// Applies layer transform (position/scale/rotation/anchor_point).
///
/// Currently a pass-through; real 2D affine transform implementation will
/// delegate to the GPU transform pipeline.
pub struct CompTransformProcessor;

impl CompTransformProcessor {
    pub fn from_node(_node: &Node) -> Self {
        Self
    }
}

impl NodeProcessor for CompTransformProcessor {
    fn process(
        &self,
        _ctx: &EvalContext,
        inputs: &[&dyn NodeData],
    ) -> anyhow::Result<Box<dyn NodeData>> {
        pass_through_fb(inputs, "comp.transform")
    }
}

/// Applies layer opacity.
///
/// Currently a pass-through; real implementation will multiply alpha channel.
pub struct CompOpacityProcessor;

impl CompOpacityProcessor {
    pub fn from_node(_node: &Node) -> Self {
        Self
    }
}

impl NodeProcessor for CompOpacityProcessor {
    fn process(
        &self,
        _ctx: &EvalContext,
        inputs: &[&dyn NodeData],
    ) -> anyhow::Result<Box<dyn NodeData>> {
        pass_through_fb(inputs, "comp.opacity")
    }
}

/// Blend-mode merge for layer compositing.
///
/// Currently a pass-through returning the foreground input; real
/// implementation will use GPU alpha compositing with the appropriate
/// blend mode.
pub struct CompMergeProcessor {
    _blend_mode: String,
}

impl CompMergeProcessor {
    pub fn from_node(node: &Node) -> Self {
        Self {
            _blend_mode: node
                .type_key
                .strip_prefix("comp.merge.")
                .unwrap_or("normal")
                .to_string(),
        }
    }
}

impl NodeProcessor for CompMergeProcessor {
    fn process(
        &self,
        _ctx: &EvalContext,
        inputs: &[&dyn NodeData],
    ) -> anyhow::Result<Box<dyn NodeData>> {
        // inputs[0] = background, inputs[1] = foreground
        // Return foreground if available, else background.
        if inputs.len() >= 2
            && let Some(fb) = crate::gpu_util::clone_frame_value(inputs[1])
        {
            return Ok(fb);
        }
        pass_through_fb(inputs, "comp.merge")
    }
}

/// Effect chain pass-through (placeholder for subgraph evaluation).
pub struct CompEffectsProcessor;

impl CompEffectsProcessor {
    pub fn from_node(_node: &Node) -> Self {
        Self
    }
}

impl NodeProcessor for CompEffectsProcessor {
    fn process(
        &self,
        _ctx: &EvalContext,
        inputs: &[&dyn NodeData],
    ) -> anyhow::Result<Box<dyn NodeData>> {
        pass_through_fb(inputs, "comp.effects")
    }
}

// ===========================================================================
// Helpers
// ===========================================================================

fn pass_through_fb(inputs: &[&dyn NodeData], label: &str) -> anyhow::Result<Box<dyn NodeData>> {
    if let Some(input) = inputs.first()
        && let Some(fb) = crate::gpu_util::clone_frame_value(*input)
    {
        return Ok(fb);
    }
    anyhow::bail!("{label}: no valid FrameBuffer input")
}
