name = "workspace.preset.edit"

[layout]
type = "split"
orientation = "horizontal"
ratio = 0.8199999928474426

[layout.first]
type = "split"
orientation = "vertical"
ratio = 0.6499999761581421

[layout.first.first]
type = "split"
orientation = "horizontal"
ratio = 0.20000000298023224

[layout.first.first.first]
type = "leaf"
panel = "outliner"

[layout.first.first.second]
type = "leaf"
panel = "viewer"

[layout.first.second]
type = "split"
orientation = "horizontal"
ratio = 0.3499999940395355

[layout.first.second.first]
type = "leaf"
panel = "node_graph"

[layout.first.second.second]
type = "leaf"
panel = "timeline"

[layout.second]
type = "leaf"
panel = "properties"
